### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by thefunkyduck** [nayutaya/msgpack-pure#1]
Hi

Could you please specify a license for this code, e.g. Apache 2.0 (same as msgpack). 

Thanks

**Comment by jpias** [comment]
Hi,

+1 License would be very helpful. Could you please add it?

Thanks,
Jakub

**Comment by nayutaya** [comment]
Added!
[51842df]

**Comment by jpias** [comment]
Thank you Good Sir!
